### ISSUE TITLE
Several minor suggestions

### ISSUE THREAD

**Issue by GerretS** [bellanich/git-cheatsheet#1]
Very nice work Bella!

If I can make a few minor suggestions for improvement:

- In the "Branches" chapter you mention a "master" branch a few times. Now, most of the git-using world has decided to rename this branch to "main" wherever possible, because of the old name's slavery connotations. You will still see "master" in some older projects, mainly because changing the name of the main branch is a risky process, especially if you have things like automatic deployment scripts based on this.

- In Git Conventions you mention that HEAD^3 is shorthand for 3 commits before current HEAD. This is a very tricky one, but this is not quite true. HEAD~3 (with a tilde) is 3 commits back, but can only deal with a linear history. On the other hand HEAD^3 (with the hat) can deal with a branching history and may refer to a commit only 2 steps back from the current position, but along a side branch. See: https://stackoverflow.com/a/2222920
   - Personally I think going up a branching history is rather confusing and once I need to do that I tend to switch to a Git UI tool in my IDE instead. So I use ~ instead of ^ and switch to the UI once ^ becomes necessary.

- As a next step, it might be good to add a section about remote Git repository management tools such as Github and Gitlab. If only because they have functionality that is not part of basic Git, such as Github Actions but also Pull Requests/Merge Requests. People confuse them with Git quite often but they're quite different.

**Comment by bellanich** [comment]
Hi Garret,

Thanks for the kind words and taking the time to provide the thoughtful feedback. I've taken your suggestions and implemented them in this PR: https://github.com/bellanich/git-cheatsheet/pull/2

I've implemented all suggested changes, but have chosen not to do a deep-dive on remote Git repository management tools. I've introduced this concept, but kept it a high-level. This **(a)** keeps the cheatsheet short and **(b)** ensures that it doesn't become too specific to a given hosting service.

Cheers, Bella
